### ISSUE TITLE
Continuous matrices X

### ISSUE THREAD

**Issue by haziqj** [bioDS/Pint#2]
Nice work! I was looking for an R package that could do three-way interactions LASSO and came across this one. Asking if there will be support for continuous X? :) Tried this and most times it would crash R and once in a while it actually gives a result.

**Comment by kollienne** [comment]
It might happen, I have some thoughts about how to implement this, but I can't make any promises.

**Comment by kollienne** [comment]
I've only tested it in a few small cases, but this is added now.
